name: Linting

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master, dev]

defaults:
  run:
    working-directory: ./

jobs:
  php:
    timeout-minutes: 2
    name: PHP Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl
          coverage: none
      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --working-dir=tools/php-cs-fixer
      - name: Lint PHP
        run: bash -c "exit $(($(tools/php-cs-fixer/vendor/bin/php-cs-fixer fix -n | wc -l) - 2))"
